version: '3.4'
services:
  nginx:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  back:
    build: 
      context: ./crypto-back/
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=back${api}
  front:
    build: 
      context: ./crypto-front/
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=front${api}
    depends_on:
      - back