version: '3.4'
services:
  nginx:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
    expose:
      - 80
  back:
    build: 
      context: ./crypto-back/
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=back${domain} 
    expose:
      - 9090
  front:
    build: 
      context: ./crypto-front/
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=front${domain}
    depends_on:
      - back
    expose:
      - 3000